epochs: 32
patience: 10
imgsz: 800
batch: 4
device: 0
workers: 0
amp: true
cache: false
optimizer: AdamW
lr0: 0.0008
lrf: 0.05
weight_decay: 0.0005
cos_lr: true
warmup_epochs: 2.0
freeze: 11
seed: 42
deterministic: true
fliplr: 0.0
flipud: 0.0
degrees: 0.0
shear: 0.0
perspective: 0.0
translate: 0.02
scale: 0.12
mosaic: 0.0
mixup: 0.0
copy_paste: 0.0
hsv_h: 0.0
hsv_s: 0.10
hsv_v: 0.10
close_mosaic: 0
plots: true
save: true
save_period: 10
max_det: 30
verbose: true
